Repository OutdatedGuy/internet_connection_checker_plus, pull requests merged in 2024-12, with the labels that each got.

#65 chore: updated example app to flutter v3.27
  .gitignore
  .metadata
  example/.gitignore
  example/.metadata
  example/android/app/build.gradle
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/android/settings.gradle
  example/ios/Podfile.lock
  example/linux/CMakeLists.txt
  example/linux/runner/CMakeLists.txt
  example/linux/runner/main.cc
  example/linux/runner/my_application.cc
  example/linux/runner/my_application.h
  example/macos/Podfile.lock
  example/macos/Runner/AppDelegate.swift
  example/pubspec.lock
  example/pubspec.yaml
  example/web/index.html
  pubspec.yaml
Labels: dependencies

#63 feat: allow changing check interval
  lib/src/internet_connection.dart
  test/internet_connection_test.dart
Labels: enhancement

#67 feat: add strict mode for internet connectivity checks
  lib/src/internet_connection.dart
  test/internet_connection_test.dart
Labels: enhancement

#68 feat: added topics and funding file for pub.dev
  pubspec.yaml
Labels: documentation
